# Generated by Django 5.0.3 on 2025-07-31 06:09

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='images/default_user.jpg', null=True, upload_to=users.models.generateImagePath),
        ),
    ]
