# Generated by Django 5.2.4 on 2025-08-01 05:51

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='images/users/default_user.jpg', null=True, upload_to=users.models.generateImagePath),
        ),
    ]
