# Generated by Django 5.2.4 on 2025-08-01 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='priority',
            field=models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('IP', 'In Progress'), ('CP', 'Completed'), ('P', 'Pending'), ('C', 'Canceled')], default='P', max_length=2),
        ),
    ]
