# Generated by Django 5.2.4 on 2025-08-01 05:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=11),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Canceled', 'Canceled'), ('Pending', 'Pending')], default='Pending', max_length=11),
        ),
        migrations.AlterField(
            model_name='project',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, null=True, related_name='assigned_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
